# Generated by Django 3.2.25 on 2024-10-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address_1',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address_2',
            new_name='street',
        ),
    ]
