# Generated by Django 3.2.25 on 2024-11-29 11:43

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=25, validators=[checkout.models.validate_no_numbers]),
        ),
    ]
